const $=id=>document.getElementById(id);let previewMode=!TrackIT.configured;
const fields={tracking_code:'trackingCode',sender_name:'senderName',recipient_name:'recipientName',origin:'origin',destination:'destination',delivery_address:'deliveryAddress',package_type:'packageType',weight:'weight',declared_value:'declaredValue',shipping_fee:'shippingFee',currency:'currency',transit_hub:'transitHub',customs_location:'customsLocation',delivery_city:'deliveryCity',received_date:'receivedDate',in_transit_date:'inTransitDate',customs_date:'customsDate',out_for_delivery_date:'outForDeliveryDate',delivery_date:'deliveryDate',manual_status:'manualStatus',notes:'notes'};
function msg(t,ok=false){$('loginMessage').className=ok?'success':'error';$('loginMessage').textContent=t}
function showAdmin(){ $('authView').classList.add('hidden');$('adminView').classList.remove('hidden');$('modeBanner').classList.toggle('hidden',!previewMode);clearForm();loadList() }
async function init(){if(!TrackIT.configured){$('previewBanner').classList.remove('hidden');$('loginFields').classList.add('hidden');$('previewBtn').classList.remove('hidden');return}const {data}=await TrackIT.client.auth.getSession();if(data.session)showAdmin()}
$('previewBtn').onclick=showAdmin;
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();msg('');try{const {error}=await TrackIT.client.auth.signInWithPassword({email:$('adminEmail').value.trim(),password:$('adminPassword').value});if(error)throw error;previewMode=false;showAdmin()}catch(e){msg(e.message||'Sign-in failed.')}});
$('logoutBtn').onclick=async()=>{if(TrackIT.client&&!previewMode)await TrackIT.client.auth.signOut();location.reload()};
$('generateBtn').onclick=()=>{$('trackingCode').value=TrackIT.genCode()};$('clearBtn').onclick=clearForm;
function clearForm(){Object.values(fields).forEach(id=>{if($(id))$(id).value=''});$('currency').value='USD';$('manualStatus').value='Auto';$('trackingCode').value=TrackIT.genCode();$('editingCode').value='';$('saveBtn').textContent='Save Package'}
function collect(){const p={};for(const [k,id] of Object.entries(fields))p[k]=$(id).value.trim();p.declared_value=p.declared_value?Number(p.declared_value):null;p.shipping_fee=p.shipping_fee?Number(p.shipping_fee):null;return p}
$('packageForm').addEventListener('submit',async e=>{e.preventDefault();const p=collect();const btn=$('saveBtn');btn.disabled=true;btn.textContent='Saving…';try{const oldCode=$('editingCode').value.trim();await TrackIT.adminUpsert(p);if(oldCode&&oldCode!==p.tracking_code)await TrackIT.adminDelete(oldCode);clearForm();await loadList()}catch(e){alert(e.message||'Could not save shipment.')}finally{btn.disabled=false;btn.textContent='Save Package'}});
async function loadList(){const root=$('packageList');root.innerHTML='<div class="muted">Loading…</div>';try{const rows=await TrackIT.adminList();root.innerHTML=rows.map(p=>`<article class="package-card"><div class="package-card-head"><div><div class="package-code">${TrackIT.esc(p.tracking_code)}</div><div style="font-weight:850;margin-top:3px">${TrackIT.esc(p.recipient_name||'Unnamed recipient')}</div><div class="package-meta">${TrackIT.esc(p.destination||'No destination')} · ${TrackIT.esc(TrackIT.fmt(p.delivery_date))}</div></div><span class="small-pill">${TrackIT.esc(TrackIT.status(p))}</span></div><div class="package-actions"><button data-edit="${TrackIT.esc(p.tracking_code)}">Edit</button><a href="index.html?tracking=${encodeURIComponent(p.tracking_code)}" target="_blank"><button type="button">Preview</button></a><button data-delete="${TrackIT.esc(p.tracking_code)}" style="color:#b42318">Delete</button></div></article>`).join('')||'<div class="muted">No shipment records yet.</div>';root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRow(rows.find(p=>p.tracking_code===b.dataset.edit)));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRow(b.dataset.delete))}catch(e){root.innerHTML=`<div class="error">${TrackIT.esc(e.message||'Could not load shipments.')}</div>`}}
function editRow(p){if(!p)return;for(const [k,id] of Object.entries(fields))$(id).value=p[k]??'';$('editingCode').value=p.tracking_code;$('saveBtn').textContent='Update Package';scrollTo({top:0,behavior:'smooth'})}
async function deleteRow(code){if(!confirm(`Delete ${code}?`))return;try{await TrackIT.adminDelete(code);await loadList()}catch(e){alert(e.message||'Could not delete shipment.')}}
init();
